{% set name = "rdfpy" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdfpy-{{ version }}.tar.gz
  sha256: 99ac9f002148b09afc763bf86ccae094236f41a9762498760f5d28d021a2ba57

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - rdfpy
    - tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/by256/rdfpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'rdfpy is a Python library for fast computation of 2D and 3D radial distribution functions.'
  description: |
    rdfpy is a Python library for fast computation of 2D and 3D radial 
    distribution functions.
  doc_url: https://rdfpy.readthedocs.io/
  dev_url: https://github.com/by256/rdfpy

extra:
  recipe-maintainers:
    - jan-janssen
